apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnmake-ms
spec:
  selector:
    matchLabels:
      app: learnmake-ms
  template:
    metadata:
      labels:
        app: learnmake-ms
    spec:
      containers:
      - name: learnmake-ms
        image: gcr.io/catpet-205415/learnmake-microservices:1.0.8
        ports:
        - containerPort: 8080
        #resources:
        #  limits:
        #    memory: "200Mi"
        #  requests:
        #    memory: "100Mi"
        livenessProbe:
          httpGet:
            port: 8080
            path: /api/pulse
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 2

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: learnmake-ms-ingress
spec:
  backend:
    serviceName: learnmake-ms
    servicePort: 8080
